pub fn auto_sync() {
    let _ = libmorpheus::fs::sync();
}

pub fn usage(cmd: &str) -> Option<&'static str> {
    Some(match cmd {
        "cd" => concat!(
            "cd — change working directory\n",
            "\n",
            "USAGE\n",
            "  cd [path]\n",
            "  cd -        Return to previous directory\n",
            "\n",
            "With no argument, changes to /.\n",
            "Supports relative paths, . and .. components.\n",
        ),
        "pwd" => concat!(
            "pwd — print working directory\n",
            "\n",
            "USAGE\n",
            "  pwd\n",
            "\n",
            "Prints the absolute path of the current directory.\n",
        ),
        "echo" => concat!(
            "echo — print arguments\n",
            "\n",
            "USAGE\n",
            "  echo [args...]\n",
            "\n",
            "Prints each argument separated by spaces, followed by a newline.\n",
            "Supports output redirection: echo hello > file.txt\n",
        ),
        "clear" => concat!(
            "clear — clear the terminal screen\n",
            "\n",
            "USAGE\n",
            "  clear\n",
        ),
        "exit" | "quit" => concat!(
            "exit — terminate the shell\n",
            "\n",
            "USAGE\n",
            "  exit [code]\n",
            "\n",
            "Exits with the given status code (default 0).\n",
        ),
        "help" => concat!(
            "help — display help information\n",
            "\n",
            "USAGE\n",
            "  help          Show all commands\n",
            "  help <cmd>    Show help for a specific command\n",
            "\n",
            "You can also use: <cmd> --help\n",
        ),
        "ls" => concat!(
            "ls — list directory contents\n",
            "\n",
            "USAGE\n",
            "  ls [-la] [path]\n",
            "\n",
            "OPTIONS\n",
            "  -l    Long format: type, size, version count, name\n",
            "  -a    Show all entries (default, accepted for compat)\n",
            "\n",
            "Flags can be combined: -la, -al, etc.\n",
            "Without -l, prints names in compact format.\n",
            "Directories are shown with a trailing /.\n",
        ),
        "cat" => concat!(
            "cat — display file contents\n",
            "\n",
            "USAGE\n",
            "  cat <file> [file2...]\n",
            "\n",
            "Reads each file as UTF-8 text and prints to stdout.\n",
            "Multiple files are concatenated in order.\n",
        ),
        "mkdir" => concat!(
            "mkdir — create a directory\n",
            "\n",
            "USAGE\n",
            "  mkdir <path>\n",
            "\n",
            "Creates a new directory. Parent directories must exist.\n",
            "Changes are automatically synced to disk.\n",
        ),
        "rm" => concat!(
            "rm — remove a file\n",
            "\n",
            "USAGE\n",
            "  rm <path>\n",
            "\n",
            "Removes a file from HelixFS. Cannot remove directories\n",
            "(use rmdir for empty directories).\n",
            "Changes are automatically synced to disk.\n",
        ),
        "rmdir" => concat!(
            "rmdir — remove an empty directory\n",
            "\n",
            "USAGE\n",
            "  rmdir <path>\n",
            "\n",
            "Removes an empty directory from HelixFS.\n",
            "Fails if the directory is not empty.\n",
            "Changes are automatically synced to disk.\n",
        ),
        "mv" => concat!(
            "mv — rename or move a file\n",
            "\n",
            "USAGE\n",
            "  mv <source> <destination>\n",
            "\n",
            "Renames or moves a file or directory.\n",
            "Changes are automatically synced to disk.\n",
        ),
        "cp" => concat!(
            "cp — copy a file\n",
            "\n",
            "USAGE\n",
            "  cp <source> <destination>\n",
            "\n",
            "Copies file contents. Does not copy directories.\n",
            "Changes are automatically synced to disk.\n",
        ),
        "touch" => concat!(
            "touch — create an empty file\n",
            "\n",
            "USAGE\n",
            "  touch <path>\n",
            "\n",
            "Creates the file if it doesn't exist. No-op if it does.\n",
            "Changes are automatically synced to disk.\n",
        ),
        "stat" => concat!(
            "stat — display file metadata\n",
            "\n",
            "USAGE\n",
            "  stat <path>\n",
            "\n",
            "Shows HelixFS metadata: type, size, key hash, LSN,\n",
            "version count, and flags.\n",
        ),
        "write" => concat!(
            "write — write text to a file\n",
            "\n",
            "USAGE\n",
            "  write <path> <text...>\n",
            "\n",
            "Creates or overwrites the file with the given text.\n",
            "All arguments after the path are joined with spaces.\n",
            "Changes are automatically synced to disk.\n",
        ),
        "sync" => concat!(
            "sync — flush HelixFS journal to disk\n",
            "\n",
            "USAGE\n",
            "  sync\n",
            "\n",
            "Forces all pending log entries to stable storage.\n",
            "Note: write operations auto-sync, so manual sync is\n",
            "rarely needed.\n",
        ),
        "ps" => concat!(
            "ps — list running processes\n",
            "\n",
            "USAGE\n",
            "  ps\n",
            "\n",
            "Displays PID, PPID, state, CPU ticks, and name\n",
            "for all processes in the system.\n",
            "\n",
            "States: Ready, Running, Blocked, Zombie, Dead\n",
        ),
        "kill" => concat!(
            "kill — send a signal to a process\n",
            "\n",
            "USAGE\n",
            "  kill <pid> [signal]\n",
            "  kill -<signal> <pid>\n",
            "\n",
            "SIGNALS\n",
            "  2   SIGINT    Interrupt\n",
            "  9   SIGKILL   Unconditional kill\n",
            "  15  SIGTERM   Graceful termination (default)\n",
            "  18  SIGCONT   Continue stopped process\n",
            "  19  SIGSTOP   Stop process\n",
        ),
        "sysinfo" => concat!(
            "sysinfo — display system information\n",
            "\n",
            "USAGE\n",
            "  sysinfo\n",
            "\n",
            "Shows uptime, process count, physical memory,\n",
            "kernel heap usage, and TSC frequency.\n",
        ),
        "sleep" => concat!(
            "sleep — pause execution\n",
            "\n",
            "USAGE\n",
            "  sleep <milliseconds>\n",
            "\n",
            "Suspends the shell for the given duration.\n",
        ),
        "true" => concat!(
            "true — return success\n",
            "\n",
            "USAGE\n",
            "  true\n",
            "\n",
            "Exits with status 0.\n",
        ),
        "false" => concat!(
            "false — return failure\n",
            "\n",
            "USAGE\n",
            "  false\n",
            "\n",
            "Exits with status 1.\n",
        ),
        _ => return None,
    })
}
